### ISSUE TITLE
 autoFocus failed

### ISSUE THREAD

**Issue by fylw** [smzhldr/AGLFramework#2]
Process: com.aglframework.smzh.agl_framework, PID: 12403
    java.lang.RuntimeException: Unable to resume activity {com.aglframework.smzh.agl_framework/com.aglframework.smzh.agl_framework.activity.CameraActivity}: java.lang.RuntimeException: autoFocus failed
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3874)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3906)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1847)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6899)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: java.lang.RuntimeException: autoFocus failed
        at android.hardware.Camera.native_autoFocus(Native Method)
        at android.hardware.Camera.autoFocus(Camera.java:1476)
        at com.aglframework.smzh.camera.AGLCamera.open(AGLCamera.java:72)
        at com.aglframework.smzh.agl_framework.presenter.CameraPresenter.onResume(CameraPresenter.java:53)
        at com.aglframework.smzh.agl_framework.activity.CameraActivity.onResume(CameraActivity.java:85)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
        at android.app.Activity.performResume(Activity.java:7408)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3866)

**Comment by smzhldr** [comment]
thanks, Generally, try... Catch is used to protect hardware related operations
